name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "d1"
database_id = "aff8e754-e1e4-4f6e-9b20-01524e5e00c2"